import Head from 'next/head'
import { useEffect, useState } from "react";
import { BsFillMoonStarsFill } from 'react-icons/bs';
import Footer from '../../components/Footer';
import FullScreenNavbar from '../../components/FullScreenNavbar';
import Link from "next/link";
import Image from 'next/image';
import prototype from './img/rhbprototype.png'
import cert from './img/rhbcert.png'
import Navbar from '../../components/Navbar';

const RHB2023 = () => {
    const [darkMode, setDarkMode] = useState(
        typeof window !== 'undefined' ? JSON.parse(localStorage.getItem("darkMode") || false) : false
      );
    
      useEffect(() => {
        localStorage.setItem("darkMode", JSON.stringify(darkMode));
      }, [darkMode]);
    return (
    <div className={darkMode ? "dark" : ""}>
        <Head>
        <title>Dun Yan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
            <section className="min-h-screen">
            <div className={darkMode ? "dark" : ""}>
                <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
            </div>            
            <div className="pt-10 pb-5">                
                <h1 className="text-center text-4xl py-2 text-cyan-600 dark:text-cyan-500 font-medium md:text-4xl">RHB Hack 2023</h1>
            </div>

            {/* Hackathon info */}
            <div className='flex justify-center'>

            <div className='text-left pt-10 pl-1 pb-2'>           
            <figure className='flex justify-center'>  
                <Image src={prototype} alt='prototype img' className='rounded-xl h-1/2 w-1/1 md:w-2/3'/>
            </figure> 
            <figcaption className="mt-2 text-sm text-center text-gray-500 dark:text-gray-400">Figma prototype</figcaption>
                <h2 className="text-center text-2xl py-10 max-w-xl mx-auto text-gray-700 dark:text-gray-300 font-medium md:text-3xl">Zee - Expense Management Feature for RHB Mobile Banking App</h2>          
                <p className="text-md py-3 leading-8 max-w-xl mx-auto text-gray-700 dark:text-gray-300">Welcome to Zee, a new expense management prototype feature within the RHB mobile banking app. With its card-swiping mechanism, Zee aims to make expense categorization more efficient for users, allowing them to easily track and manage their expenses.</p>                        
                <p className="text-md py-3 leading-8 max-w-xl mx-auto text-gray-700 dark:text-gray-300">This project is a prototype and is not officially endorsed or supported by RHB Bank.</p> 
            <figure className='flex justify-center'>  
                <Image src={cert} alt='prototype img' className='rounded-xl h-1/3 w-1/1 md:w-1/3'/>
            </figure> 
            <figcaption className="mt-2 text-sm text-center text-gray-500 dark:text-gray-400">RHB Certificate</figcaption>
                <div className='max-w-xl mx-auto'>
                    <h3 className='text-start text-xl pt-10 text-gray-700 dark:text-gray-300 font-medium md:text-xl'>Tech Stack:</h3>
                    <p className='text-gray-700 dark:text-gray-300 text-md max-w-xl mx-auto'>NextJS, React, Tailwind, CSS, ChakraUI</p>                    
                </div>   
                <div className='max-w-xl mx-auto'>
                    <h3 className='text-start text-xl pt-10 max-w-xl mx-auto text-gray-700 dark:text-gray-300 font-medium md:text-xl'>Github:</h3>
                    <span><a href='https://github.com/dunyanong/Zee' className="text-md max-w-xl mx-auto text-cyan-600" target='_blank'>link</a></span>
                </div>           
            </div>

            </div>

            <Footer />
        </section>
        </main>
        </div>
    );
    
}

export default RHB2023