import { useEffect, useState } from "react";
import Image from 'next/image';
import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import Footer from '../../components/Footer';
import FullScreenNavbar from '../../components/FullScreenNavbar';
import Link from "next/link";
import Navbar from '../../components/Navbar';

import async from '../../data/certs/Asynchronous Programming Course.png';
import HTML from '../../data/certs/HTML.png';
import CSS from '../../data/certs/CSS.png';
import Javascript from '../../data/certs/JavaScript.png';
import pythonBlockchain from '../../data/certs/python-blockchain.png';

const images = [
  {
    src: async,
    alt: 'Image 1',
    description: 'Asynchronous programming certificate from Codecademy',
  },
  {
    src: HTML,
    alt: 'Image 2',
    description: 'HTML certificate from Codecademy',
  },
  {
    src: CSS,
    alt: 'Image 3',
    description: 'CSS certificate from Codecademy',
  },
  {
    src: Javascript,
    alt: 'Image 4',
    description: 'Javascript certificate from Codecademy',
  },
  {
    src: pythonBlockchain,
    alt: 'Image 5',
    description: 'Basics of blockchain certificate from Codecademy',
  },    
];

const Certs = () => {
const [darkMode, setDarkMode] = useState(
    typeof window !== 'undefined' ? JSON.parse(localStorage.getItem("darkMode") || false) : false
    );    
  const [hoveredIndex, setHoveredIndex] = useState(-1);

  useEffect(() => {
    localStorage.setItem("darkMode", JSON.stringify(darkMode));
  }, [darkMode]);

  return (
    <div className={darkMode ? "dark" : ""}>
        <Head>
        <title>Dun Yan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
            <section className="min-h-screen">
            <div className={darkMode ? "dark" : ""}>
            <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
            </div>            

            <div className="pt-10 pb-5">
                <h2 className="text-center text-4xl py-2 text-cyan-600 dark:text-cyan-500 font-medium md:text-4xl">Certificates</h2>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10 pt-10">
            {images.map((image, index) => (
            <div
                key={index}
                className="relative cursor-pointer"
                onMouseEnter={() => setHoveredIndex(index)}
                onMouseLeave={() => setHoveredIndex(-1)}
            >
                <Image
                src={image.src}
                alt={image.alt}
                width={500}
                height={500}
                className="rounded-lg"
                />
                {hoveredIndex === index && (
                <div className="absolute top-0 left-0 w-full h-full bg-gray-800 bg-opacity-50 rounded-lg flex items-center justify-center">
                <p className="text-white">{image.description}</p>
                </div>
                )}
            </div>
            ))}
            </div>
            <Footer />
            </section>
        </main>
        </div>
    );
};

export default Certs;