import Head from 'next/head'
import { useState, useEffect } from "react";
import Footer from '../../components/Footer';
import FullScreenNavbar from '../../components/FullScreenNavbar';
import Link from "next/link";
import Timeline from '../../components/Timeline';

// all icons
import { IoMdDownload } from 'react-icons/io';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { FaLink } from 'react-icons/fa'

const About = () => {
  const [darkMode, setDarkMode] = useState(
    typeof window !== 'undefined' ? JSON.parse(localStorage.getItem("darkMode") || false) : false
  );

  useEffect(() => {
    localStorage.setItem("darkMode", JSON.stringify(darkMode));
  }, [darkMode]);

    return (
      <div className={darkMode ? "dark" : ""}>
      <Head>
      <title>Dun Yan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
          <section className="min-h-screen">
          <div className={darkMode ? "dark" : ""}>
            <nav className="navbar py-5 mb-12">
            <div className="navbar-start md:hidden">            
                <FullScreenNavbar />
            </div>
            <div className="navbar-start hidden md:flex">
                <ul className="flex justify-between gap-5">
                <li>
                    <Link href="/" legacyBehavior>
                    <a className="text-base  font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">Home</a>
                    </Link> 
                </li>
                <li>
                    <Link href="/about" legacyBehavior>
                    <a className="text-base  font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">About</a>
                    </Link> 
                </li>
                <li>
                    <Link legacyBehavior href="/blogs">
                    <a className="text-base font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">Blogs</a>
                    </Link>               
                </li>
                </ul>
            </div>
            <div className="navbar-end">
                <ul className="flex items-center">
                  <li><BsFillMoonStarsFill className="cursor-pointer text-slate-600 dark:text-slate-200" onClick={() => setDarkMode(!darkMode)}/></li>
                </ul>
            </div>
            </nav>
            </div>                  

            {/* About */}
            <div className="pt-10">
              <h2 className="text-center text-4xl pb-2 text-cyan-600 dark:text-cyan-500 font-medium">About Me</h2>
              <hr className="w-48 h-1 mx-auto mb-4 bg-gray-100 border-0 rounded my-6 md:my-10 dark:bg-gray-700"></hr>
            </div>  

            {/*Timeline!*/}
            <Timeline />           
            {/* My Personal Statement and Resume */}
            <div className="pt-10">
              <div className="text-left pl-1">
                <h2 className="text-2xl text-cyan-600 dark:text-cyan-500 font-medium md:text-2xl">My Personal Statement & Resume</h2>
              </div>
              <hr className="h-px mt-2 mb-4 bg-gray-100 border-0 dark:bg-gray-700"></hr>
              <div className="flex justify-start items-center">              
                <Link href="/about/personalstatement" legacyBehavior>
                  <a className="flex justify-between mr-3 ml-1 items-center">
                    <span className="inline-block text-gray-600 dark:text-gray-300 mr-1">Resume</span>
                    <IoMdDownload className="inline-block text-gray-600 dark:text-gray-300 mx-1" />
                  </a>
                </Link>  
                <Link href="/about/personalstatement" legacyBehavior>
                    <a className="flex justify-between ml-3 items-center">
                      <span className="inline-block text-gray-600 dark:text-gray-300 mr-1">Personal statement</span>
                      <FaLink className="inline-block text-gray-600 dark:text-gray-300 mx-1" />
                    </a>
                </Link>                
              </div>
            </div>                          

            {/*Skills*/}
            <div className="grid grid-cols-2 gap-1">

            <div className='pt-10'>
            <div className="text-left pt-10 pb-3 pl-1">
              <h2 className="text-2xl text-cyan-600 dark:text-cyan-500 font-medium md:text-2xl">Specialised in:</h2>
            </div>
            <ul className="max-w-md space-y-1 text-gray-600 dark:text-gray-300">
                <li className="flex items-center">
                    <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    Javascript
                </li>
                <li className="flex items-center">
                    <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    HTML
                </li>
                <li className="flex items-center">
                <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    React
                </li>
                <li className="flex items-center">
                <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    NextJS
                </li>
                <li className="flex items-center">
                <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    Tailwind
                </li>
            </ul>
            </div>

            <div className='pt-10'>
            <div className="text-left pt-10 pb-3 pl-1">
              <h2 className="text-2xl text-cyan-600 dark:text-cyan-500 font-medium md:text-2xl">Decent with:</h2>
            </div>
            <ul className="max-w-md space-y-1 list-inside text-gray-600 dark:text-gray-300">
                <li className="flex items-center">
                <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    Bootstrap
                </li>
                <li className="flex items-center">
                <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    NodeJS
                </li>
                <li className="flex items-center">
                <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    Express
                </li>
                <li className="flex items-center">
                <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    MongoDB
                </li>
                <li className="flex items-center">
                <svg className="w-4 h-4 mr-1.5 text-green-500 dark:text-green-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                    CSS
                </li>
            </ul>
            </div>            
            </div>
            <Footer />
        </section>
      </main>
      </div>
    );
}
 
export default About;
