import Head from 'next/head'
import { useState, useEffect } from "react";
import Footer from '../../components/Footer';
import FullScreenNavbar from '../../components/FullScreenNavbar';
import Link from "next/link";
import Timeline from '../../components/Timeline';

// all icons
import { IoMdDownload } from 'react-icons/io';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { FaLink } from 'react-icons/fa'
import Navbar from '../../components/Navbar';

const About = () => {

    return (
      <div>
      <Head>
      <title>Dun Yan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 lg:px-80 bg-black py-6">
          <section className="min-h-screen">
          <div>
            <Navbar />
          </div>                  

            {/* About */}
            <div className="pt-10">
              <h1 class="font-bold text-3xl md:text-5xl tracking-tight mb-4 text-white">Hello 👋 !</h1>
              <p class="text-xl text-gray-400 mb-4">I am a Software Engineer who likes web development and performance optimization.</p>
            </div>  

            {/*Timeline!*/}
            <Timeline />           
            {/* My Personal Statement and Resume */}
            <div className="pt-10">
              <div className="text-left pl-1">
                <h2 className="text-2xl text-cyan-500 font-medium md:text-2xl">My Personal Statement & Resume</h2>
              </div>
              <hr className="h-px mt-2 mb-4 bg-gray-700 border-0"></hr>
              <div className="flex justify-start items-center">              
                <a className="flex justify-between mr-3 ml-1 items-center" href='https://drive.google.com/file/d/1Ht0urYBCQgHCizLmCsGT3VmaAbbPN1e4/view?usp=share_link' target='_blank'>
                  <span className="inline-block text-gray-300 mr-1">Resume</span>
                  <IoMdDownload className="inline-block text-gray-300 mx-1" />
                </a>
 
                <Link href="/about/personalstatement" legacyBehavior>
                    <a className="flex justify-between ml-3 items-center">
                      <span className="inline-block text-gray-300 mr-1">Personal statement</span>
                      <FaLink className="inline-block text-gray-300 mx-1" />
                    </a>
                </Link>                
              </div>
            </div>                          
            <Footer />
        </section>
      </main>
      </div>
    );
}
 
export default About;
