import Head from 'next/head'
import { useState, useEffect } from "react";
import Footer from '../../components/Footer';
import FullScreenNavbar from '../../components/FullScreenNavbar';
import Link from "next/link";
import Timeline from '../../components/Timeline';

// all icons
import { IoMdDownload } from 'react-icons/io';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { FaLink } from 'react-icons/fa'
import Navbar from '../../components/Navbar';

const About = () => {
  const [darkMode, setDarkMode] = useState(
    typeof window !== 'undefined' ? JSON.parse(localStorage.getItem("darkMode") || false) : false
  );

  useEffect(() => {
    localStorage.setItem("darkMode", JSON.stringify(darkMode));
  }, [darkMode]);

    return (
      <div className={darkMode ? "dark" : ""}>
      <Head>
      <title>Dun Yan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
          <section className="min-h-screen">
          <div className={darkMode ? "dark" : ""}>
            <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
          </div>                  

            {/* About */}
            <div className="pt-10">
              <h2 className="text-center text-4xl pb-2 text-cyan-600 dark:text-cyan-500 font-medium">About Me</h2>
              <hr className="w-48 h-1 mx-auto mb-4 bg-gray-100 border-0 rounded my-6 md:my-10 dark:bg-gray-700"></hr>
            </div>  

            {/*Timeline!*/}
            <Timeline />           
            {/* My Personal Statement and Resume */}
            <div className="pt-10">
              <div className="text-left pl-1">
                <h2 className="text-2xl text-cyan-600 dark:text-cyan-500 font-medium md:text-2xl">My Personal Statement & Resume</h2>
              </div>
              <hr className="h-px mt-2 mb-4 bg-gray-100 border-0 dark:bg-gray-700"></hr>
              <div className="flex justify-start items-center">              
                <a className="flex justify-between mr-3 ml-1 items-center" href='https://drive.google.com/file/d/1Ht0urYBCQgHCizLmCsGT3VmaAbbPN1e4/view?usp=share_link' target='_blank'>
                  <span className="inline-block text-gray-600 dark:text-gray-300 mr-1">Resume</span>
                  <IoMdDownload className="inline-block text-gray-600 dark:text-gray-300 mx-1" />
                </a>
 
                <Link href="/about/personalstatement" legacyBehavior>
                    <a className="flex justify-between ml-3 items-center">
                      <span className="inline-block text-gray-600 dark:text-gray-300 mr-1">Personal statement</span>
                      <FaLink className="inline-block text-gray-600 dark:text-gray-300 mx-1" />
                    </a>
                </Link>                
              </div>
            </div>                          
            <Footer />
        </section>
      </main>
      </div>
    );
}
 
export default About;
