import Head from 'next/head'
import { useEffect, useState } from "react";
import { BsFillMoonStarsFill } from 'react-icons/bs';
import Footer from '../../components/Footer';
import FullScreenNavbar from '../../components/FullScreenNavbar';
import Link from "next/link";

const PersonalStatement = () => {
  const [darkMode, setDarkMode] = useState(
    typeof window !== 'undefined' ? JSON.parse(localStorage.getItem("darkMode") || false) : false
  );

  useEffect(() => {
    localStorage.setItem("darkMode", JSON.stringify(darkMode));
  }, [darkMode]);
    return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
      <title>Dun Yan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
          <section className="min-h-screen">
          <div className={darkMode ? "dark" : ""}>
          <nav className="navbar py-5 mb-12">
          <div className="navbar-start md:hidden">            
              <FullScreenNavbar />
          </div>
          <div className="navbar-start hidden md:flex">
              <ul className="flex justify-between gap-5">
              <li>
                  <Link href="/" legacyBehavior>
                  <a className="text-base  font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">Home</a>
                  </Link> 
              </li>
              <li>
                  <Link href="/about" legacyBehavior>
                  <a className="text-base  font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">About</a>
                  </Link> 
              </li>
              <li>
                  <Link legacyBehavior href="/blogs">
                  <a className="text-base font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">Blogs</a>
                  </Link>               
              </li>
              </ul>
          </div>
          <div className="navbar-end">
              <ul className="flex items-center">
                <li><BsFillMoonStarsFill className="cursor-pointer text-slate-600 dark:text-slate-200" onClick={() => setDarkMode(!darkMode)}/></li>
              </ul>
          </div>
          </nav>
          </div>            

            <div className="pt-10 pb-5">
              <h2 className="text-center text-4xl py-2 text-cyan-600 dark:text-cyan-500 font-medium md:text-4xl">Personal Statement</h2>
            </div>

            {/* Personal statement */}
            <div className='text-left pt-10 pl-1 pb-2'>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">As a self-taught full-stack engineer, my journey began in November 2020 when I decided to take the initiative to learn various programming languages and technologies on my own. My focus was on mastering skills such as JavaScript, React, HTML/CSS, Node, Express, and MongoDB. Alongside these technical skills, I also honed my understanding of data structures and algorithms, which are essential tools for any engineer.</p>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">My passion for coding is complemented by a strong interest in emerging technologies such as cryptocurrency, blockchain, and artificial intelligence. I find these topics fascinating and make a point to stay updated on the latest developments in these fields. Additionally, I have an interest in electronics and semiconductors.</p>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">One of the most enjoyable aspects of being an engineer is the opportunity to network with other professionals in the industry. I find it incredibly rewarding to exchange ideas and knowledge with my peers and always strive to continue learning and growing as an engineer.</p>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">In addition to my work as an engineer, I also enjoy writing articles that explain difficult concepts in an easy-to-understand manner. Clear communication is an important skill for any engineer to possess and I take pleasure in helping others better understand complex topics.</p>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">Overall, my journey as a full-stack engineer has been a rewarding and exciting one. I am constantly learning new things and am always on the lookout for opportunities to grow and improve.</p>              
            </div>

            <Footer />
        </section>
      </main>
      </div>
    );
}
 
export default PersonalStatement;