import Head from 'next/head'
import Footer from '../../components/Footer';
import Navbar from '../../components/Navbar';

const PersonalStatement = () => {
    return (
    <div>
      <Head>
      <title>Dun Yan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 lg:px-80 bg-black py-6">
          <section className="min-h-screen">
          <div>
            <Navbar />
          </div>            

            <div className="pt-10 pb-5">
              <h2 className="text-center text-4xl py-2 text-cyan-500 font-medium md:text-4xl">Personal Statement</h2>
            </div>

            {/* Personal statement */}
            <div className='text-left pt-10 pl-1 pb-2 text-gray-300'>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto">As a self-taught full-stack engineer, my journey began in November 2020 when I decided to take the initiative to learn various programming languages and technologies on my own. My focus was on mastering skills such as JavaScript, React, HTML/CSS, Node, Express, and MongoDB. Alongside these technical skills, I also honed my understanding of data structures and algorithms, which are essential tools for any engineer.</p>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto">My passion for coding is complemented by a strong interest in emerging technologies such as cryptocurrency, blockchain, and artificial intelligence. I find these topics fascinating and make a point to stay updated on the latest developments in these fields. Additionally, I have an interest in electronics and semiconductors.</p>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto">One of the most enjoyable aspects of being an engineer is the opportunity to network with other professionals in the industry. I find it incredibly rewarding to exchange ideas and knowledge with my peers and always strive to continue learning and growing as an engineer.</p>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto">In addition to my work as an engineer, I also enjoy writing articles that explain difficult concepts in an easy-to-understand manner. Clear communication is an important skill for any engineer to possess and I take pleasure in helping others better understand complex topics.</p>              
            <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto">Overall, my journey as a full-stack engineer has been a rewarding and exciting one. I am constantly learning new things and am always on the lookout for opportunities to grow and improve.</p>              
            </div>

            <Footer />
        </section>
      </main>
      </div>
    );
}
 
export default PersonalStatement;