import Head from 'next/head'
import { useEffect, useState } from "react";
import { BsFillMoonStarsFill } from 'react-icons/bs';
import Footer from '../../components/Footer';
import FullScreenNavbar from '../../components/FullScreenNavbar';
import Link from "next/link";

const PersonalStatement = () => {
  const [darkMode, setDarkMode] = useState(
    typeof window !== 'undefined' ? JSON.parse(localStorage.getItem("darkMode") || false) : false
  );

  useEffect(() => {
    localStorage.setItem("darkMode", JSON.stringify(darkMode));
  }, [darkMode]);
    return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
      <title>Dun Yan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
          <section className="min-h-screen">
          <div className={darkMode ? "dark" : ""}>
          <nav className="navbar py-5 mb-12">
          <div className="navbar-start md:hidden">            
              <FullScreenNavbar />
          </div>
          <div className="navbar-start hidden md:flex">
              <ul className="flex justify-between gap-5">
              <li>
                  <Link href="/" legacyBehavior>
                  <a className="text-base  font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">Home</a>
                  </Link> 
              </li>
              <li>
                  <Link href="/about" legacyBehavior>
                  <a className="text-base  font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">About</a>
                  </Link> 
              </li>
              <li>
                  <Link legacyBehavior href="/blogs">
                  <a className="text-base font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">Blogs</a>
                  </Link>               
              </li>
              </ul>
          </div>
          <div className="navbar-end">
              <ul className="flex items-center">
                <li><BsFillMoonStarsFill className="cursor-pointer text-slate-600 dark:text-slate-200" onClick={() => setDarkMode(!darkMode)}/></li>
              </ul>
          </div>
          </nav>
          </div>            

            <div className="pt-10 pb-5">
              <h2 className="text-center text-4xl py-2 text-cyan-600 dark:text-cyan-500 font-medium md:text-4xl">Personal Statement</h2>
            </div>

            {/* Personal statement */}
            <div className='text-left pt-10 pl-1 pb-2'>              
              <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">As a self-taught full-stack developer, my journey began in November of 2020 when I decided to self-teach myself various programming languages and technologies. This included JavaScript, React, and HTML/CSS, as well as Node, Express, and MongoDB. In addition to these technical skills, I have also focused on learning about data structures and algorithms, which are essential tools for any developer.</p>
              <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">In addition to my passion for coding, I have a strong interest in emerging technologies such as cryptocurrency, blockchain, and artificial intelligence. I find these topics to be fascinating and enjoy staying up-to-date on the latest developments in these fields. In addition, I am also into computer hardwares and semiconductors.</p>
              <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">One of the things I enjoy most about being a developer is the opportunity to network with other professionals in the industry. I find it rewarding to exchange ideas and knowledge with my peers, and I always strive to continue learning and growing as a developer.</p>
              <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">In addition to my work as a developer, I also enjoy writing articles that explain difficult concepts in an easy-to-understand manner. I believe that clear communication is an important skill for any developer to possess, and I enjoy helping others to better understand complex topics.</p>
              <p className="text-md py-3 leading-8 md:text-l max-w-xl mx-auto text-gray-700 dark:text-gray-300">Overall, my journey as a full-stack developer has been a rewarding and exciting one. I am constantly learning new things and am always looking for opportunities to grow and improve.</p>
            </div>

            <Footer />
        </section>
      </main>
      </div>
    );
}
 
export default PersonalStatement;