import Head from 'next/head'
import { useState } from "react";
import { BsFillMoonStarsFill } from 'react-icons/bs'
import Footer from '../components/Footer';
import FullScreenNavbar from '../components/FullScreenNavbar';
import Link from "next/link";

// Blog Dataset
import BlogData from '../data/BlogData';

// map the list of Blogs
import SearchBar from '../components/SearchBar';

const Blogs = () => {
  const [darkMode, setDarkMode] = useState(false);
    const [filteredBlogs, setFilteredBlogs] = useState(BlogData);

    const handleSearch = (filteredBlogs) => {
      setFilteredBlogs(filteredBlogs);
    };
  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
      <title>Dun Yan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
          <section className="min-h-screen">
          <div className={darkMode ? "dark" : ""}>
          <nav className="navbar py-5 mb-12">
          <div className="navbar-start md:hidden">            
              <FullScreenNavbar />
          </div>
          <div className="navbar-start hidden md:flex">
              <ul className="flex justify-between gap-5">
              <li>
                  <Link href="/" legacyBehavior>
                  <a className="text-base  font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">Home</a>
                  </Link> 
              </li>
              <li>
                  <Link href="/about" legacyBehavior>
                  <a className="text-base  font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">About</a>
                  </Link> 
              </li>
              <li>
                  <Link legacyBehavior href="/blogs">
                  <a className="text-base font-semibold my-4 text-gray-800 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-600">Blogs</a>
                  </Link>               
              </li>
              </ul>
          </div>
          <div className="navbar-end">
              <ul className="flex items-center">
                <li><BsFillMoonStarsFill className="cursor-pointer text-slate-600 dark:text-slate-200" onClick={() => setDarkMode(!darkMode)}/></li>
              </ul>
          </div>
          </nav>
          </div>

          
            {/* List of Articles */}
            <div className="pt-10 pb-2">
              <h2 className="text-center text-4xl text-cyan-600 dark:text-cyan-500 font-medium md:text-4xl">Blogs</h2>
              <hr className="w-48 h-1 mx-auto mb-4 bg-gray-100 border-0 rounded my-6 md:my-10 dark:bg-gray-700"></hr>
            </div>  

            <div className='flex justify-center'>           
            <div className='md:w-3/4'>

            <SearchBar blogs={BlogData} onSearch={handleSearch} /> {/* pass the handleSearch function as a prop */}            

            </div> 
            </div>

            <Footer />
        </section>
      </main>
    </div>
  );
}
 
export default Blogs;
