import Head from 'next/head'
import { useState, useEffect } from "react";
import { BsFillMoonStarsFill } from 'react-icons/bs'
import Footer from '../components/Footer';
import FullScreenNavbar from '../components/FullScreenNavbar';
import Link from "next/link";

// Blog Dataset
import BlogData from '../data/blogs/BlogData';

// map the list of Blogs
import SearchBar from '../components/SearchBar';
import Navbar from '../components/Navbar';

const Blogs = () => {
  const [darkMode, setDarkMode] = useState(
    typeof window !== 'undefined' ? JSON.parse(localStorage.getItem("darkMode") || false) : false
  );

  useEffect(() => {
    localStorage.setItem("darkMode", JSON.stringify(darkMode));
  }, [darkMode]);

  const [filteredBlogs, setFilteredBlogs] = useState(BlogData);

  const handleSearch = (filteredBlogs) => {
    setFilteredBlogs(filteredBlogs);
  };
  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
      <title>Dun Yan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
          <section className="min-h-screen">
          <div className={darkMode ? "dark" : ""}>
            <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
          </div>
            {/* List of Articles */}
            <div className="pt-10 pb-2">
              <h2 className="text-center text-4xl text-cyan-600 dark:text-cyan-500 font-medium md:text-4xl">Blogs</h2>
              <hr className="w-48 h-1 mx-auto mb-4 bg-gray-100 border-0 rounded my-6 md:my-10 dark:bg-gray-700"></hr>
            </div>  

            <div className='flex justify-center'>           
            <div className='md:w-3/4'>

            <SearchBar blogs={BlogData} onSearch={handleSearch} /> {/* pass the handleSearch function as a prop */}            

            </div> 
            </div>

            <Footer />
        </section>
      </main>
    </div>
  );
}
 
export default Blogs;
