import Head from 'next/head'
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import Link from 'next/link';

const gallery = () => {
  return (
    <div>
    <Head>
    <title>Dun Yan</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="px-10 lg:px-80 bg-black py-6">
        <section className="min-h-screen">
        <div>
          <Navbar />
        </div>                

          {/* About */}
          <div className="flex flex-col-reverse sm:flex-row items-start">
            <div className="flex flex-col pr-8">
              <h1 className="font-bold text-3xl md:text-5xl tracking-tight mb-1 text-white">Photo Gallery 📸</h1>
              <p className="text-gray-400 py-4">These are some pictures that I gave myself as a gift to evoke feelings of nostalgia.</p>
            </div>
          </div>  

          <hr className="w-full border-1 border-gray-800 mb-8" />
          <p className="text-gray-400 py-4">Coming soon......</p>
          
          <Footer />
      </section>
    </main>
    </div>
  )
}

export default gallery